theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-S = ":write"
C-k = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
C-j = ["extend_to_line_bounds","delete_selection","paste_after"]
A-up = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"]
A-down = ["extend_to_line_bounds","delete_selection","paste_after"]

[keys.insert]
S-tab = "unindent"
C-space = "completion"
C-S = ":write"

[editor.lsp]
display-signature-help-docs = false
display-inlay-hints = true