theme = "tokyonight_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
idle-timeout = 100
completion-replace = true
completion-trigger-len = 99 # Effectively disables annoying auto completion on hover (but also disables autocomplete, need to write CTRL-SPACE to open)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
"C-." = "code_action"
esc = ["collapse_selection", "keep_primary_selection"] # Maps esc to cancel multi select and select
C-S = ":write-all"
A-k = ["extend_to_line_bounds","delete_selection","move_line_up","paste_before"] # Maps the alt-k to move line up
A-j = ["extend_to_line_bounds","delete_selection","paste_after"] # Maps the alt-j to move line down
A-up = "no_op"
A-down = "no_op"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.insert]
S-tab = "unindent"
C-space = "completion"
C-S = ":write-all"
C-s = ":write"
"C-." = "code_action"
C-h = "signature_help"

[keys.insert.j]
k = "normal_mode"