[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.vscode-json-language-server.config]
provideFormatter = true
json = { "keepLines" = { "enable" = true } }

[language-server.yaml-language-server.config]
yaml = { schemas = { kubernetes = ["/*.yaml", "/*.yml"] }, format = { enable = true } } 
